JCold_UVU_MVC_Inventory/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JCold_UVU_MVC_Inventory.Models
{
    public class Department
    {
        public int DepartmentID { get; set; }
        [Required(ErrorMessage ="Provide a Department Name")]
        [Display(Name ="Department Name")]

        public string DepName { get; set; }

        public string Location { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Telephone { get; set; }

        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Display(Name ="Website")]
        public string WebAddress { get; set; }

        [Display(Name ="Department Chair")]
        public string DepChair { get; set; }

        [Display(Name ="Department Chair Email")]
        [DataType(DataType.EmailAddress)]
        public string DepChairEmail { get; set; }
    }
}

JCold_UVU_MVC_Inventory/Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCold_UVU_MVC_Inventory.Models;

namespace JCold_UVU_MVC_Inventory.Controllers
{
    public class DepartmentsController : Controller
    {
        private JCold_UVU_MVC_InventoryDb db = new JCold_UVU_MVC_InventoryDb();

        // GET: Departments
        public ActionResult Index()
        {
            return View(db.Departments.ToList());
        }
        public ActionResult Filter()
        {
            var Departments = db.Departments;
            return View(Departments.ToList());
        }


        // GET: Departments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Departments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DepartmentID,DepName,Location,Telephone,Email,WebAddress,DepChair,DepChairEmail")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Departments.Add(department);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(department);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Departments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DepartmentID,DepName,Location,Telephone,Email,WebAddress,DepChair,DepChairEmail")] Department department)
        {
            if (ModelState.IsValid)
            {
                db.Entry(department).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(department);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Departments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Department department = db.Departments.Find(id);
            if (department == null)
            {
                return HttpNotFound();
            }
            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Department department = db.Departments.Find(id);
            db.Departments.Remove(department);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JCold_UVU_MVC_Inventory/Views/Departments/Create.cshtml
@model JCold_UVU_MVC_Inventory.Models.Department

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control", @placeholder="CS123"} })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control", @placeholder="(555)555-5555" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder="uvu@uvu.edu" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control", @placeholder="uvu.edu" } })
                @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepChair, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepChair, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepChair, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepChairEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepChairEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepChairEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCold_UVU_MVC_Inventory/Views/Departments/Delete.cshtml
@model JCold_UVU_MVC_Inventory.Models.Department

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Department Entry</h2>


<div>

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepChair)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepChair)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepChairEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepChairEmail)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()


        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Delete
        </button>
        <br />
        <br />
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-danger" role="alert">
                            This will delete all records that contain this department entry on the check out books and supplies page.
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="modal-body">
                            <div class="form-actions no-color">
                                <input type="submit" value="Yes" class="btn btn-danger" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>

JCold_UVU_MVC_Inventory/Views/Departments/Details.cshtml
@model JCold_UVU_MVC_Inventory.Models.Department

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Department</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WebAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WebAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepChair)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepChair)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DepChairEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepChairEmail)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("canEdit"))
    {
    <a href="@Url.Action("Edit", "Departments", new { id = Model.DepartmentID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
    }
    <a href="@Url.Action("Index", "Departments", new { id = Model.DepartmentID })" style="color: black" class="btn btn-sm btn-light">Back To List</a>
</p>

JCold_UVU_MVC_Inventory/Views/Departments/Edit.cshtml
@model JCold_UVU_MVC_Inventory.Models.Department

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Department</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DepartmentID)

        <div class="form-group">
            @Html.LabelFor(model => model.DepName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WebAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WebAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WebAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepChair, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepChair, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepChair, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DepChairEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DepChairEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DepChairEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCold_UVU_MVC_Inventory/Views/Departments/Filter.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.Department>

@{
    ViewBag.Title = "Filter";
}

@using GridMvc.Html

<h2><i class="fa fa-lg fa-search "></i>Filter</h2>
<br />
<br />
@if (User.IsInRole("canEdit"))
{
    <a href="@Url.Action("Create", "Departments")" style="color: white" class="btn btn-primary">Add Department</a>
    }
    <a href="@Url.Action("Index", "Departments")" style="color: white" class="btn btn-secondary">Back</a>
    <br />
    <p></p>

    @Html.Grid(Model).Columns(c =>
    {
        c.Add(d => d.DepName).Titled("Department Name");
        c.Add(d => d.Location).Titled("Location");
        c.Add(d => d.Telephone).Titled("Telephone");
        c.Add(d => d.Email).Titled("Email");
        c.Add(d => d.WebAddress).Titled("Website");
        c.Add(d => d.DepChair).Titled("Department Chair");
        c.Add(d => d.DepChairEmail).Titled("DepChairEmail");
        c.Add().Encoded(false).Sanitized(false).RenderValueAs(o => (
    @<b>
        @if (User.IsInRole("canEdit"))
                        {
            <a href="@Url.Action("Edit", "Departments", new { id = o.DepartmentID })"><i class="fa  fa-lg fa-pencil-square" title="Edit"></i></a>
                        }
        
        <a href="@Url.Action("Details", "Departments", new {id = o.DepartmentID })"><i class="fa fa-lg fa-info-circle" title="Details"></i></a>
        @if (User.IsInRole("canEdit"))
                        {
            <a href="@Url.Action("Delete", "Departments", new { id = o.DepartmentID })"><i class="fa fa-lg fa-times-circle" title="Delete"></i></a>
                        }
        
    </b>));
                }).Sortable(true).Filterable(true).WithPaging(10).WithMultipleFilters()

JCold_UVU_MVC_Inventory/Views/Departments/Index.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.Department>

@{
    ViewBag.Title = "Departments";
}

<h2><i class="fa fa-lg fa-address-card"></i> Departments</h2>

<br />
<br />
<p>
    @if (User.IsInRole("canEdit"))
    {
        <a href="@Url.Action("Create", "Departments")" style="color: white" class="btn btn-primary">Add Department</a>
    }
    <a href="@Url.Action("Filter", "Departments")" style="color: white" class="btn btn-primary">Filter</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telephone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WebAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepChair)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DepChairEmail)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DepName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telephone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WebAddress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepChair)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepChairEmail)
            </td>
            <td>
                @if (User.IsInRole("canEdit"))
                {
                    <a href="@Url.Action("Edit", "Departments", new { id = item.DepartmentID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
                }
                <a href="@Url.Action("Details", "Departments", new { id = item.DepartmentID })" style="color: black" class="btn btn-sm btn-light">Details</a>
                @if (User.IsInRole("canEdit"))
                {
                    <a href="@Url.Action("Delete", "Departments", new { id = item.DepartmentID })" style="color: black" class="btn btn-sm btn-light">Delete</a>
                }
            </td>
        </tr>
    }

</table>