JCold_UVU_MVC_Inventory/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCold_UVU_MVC_Inventory.Models;

namespace JCold_UVU_MVC_Inventory.Controllers
{
    public class BooksController : Controller
    {
        private JCold_UVU_MVC_InventoryDb db = new JCold_UVU_MVC_InventoryDb();

        // GET: Books
        //TODO make delete unavailable if a book is featured in checked out

        public ActionResult Index()
        {
            var SetAvailableBooksTrue =
            from chkb in db.CheckOutBooks
            join bk in db.Books
            on chkb.BooksID equals bk.BooksID
            where chkb.BooksID == bk.BooksID && chkb.ReturnedBook == true
            select bk;
            foreach (Books chkb in SetAvailableBooksTrue)
            {
                chkb.Available = true;
            }

            var SetAvailableBooksFalse =
            from chkb in db.CheckOutBooks
            join bk in db.Books
            on chkb.BooksID equals bk.BooksID
            where chkb.BooksID == bk.BooksID && chkb.ReturnedBook == false
            select bk;
            foreach (Books chkb in SetAvailableBooksFalse)
            {
                chkb.Available = false;
            }

            var ResetUpdateQueryBooksOnDelete =
                from st in db.Books
                where !(from ch in db.CheckOutBooks select ch.BooksID).Contains(st.BooksID)
                select st;
            foreach (Books chkb in ResetUpdateQueryBooksOnDelete)
            {
                chkb.Available = true;
            }
            db.SaveChanges();
            return View(db.Books.ToList());
        }

        public ActionResult Search(string bookTitle)
        {
            List<Books> bookList = db.Books.Where(x => x.Title.Contains(bookTitle) | x.ISBN.Contains(bookTitle) | x.ClassRoom.Contains(bookTitle)).ToList();
            return View(bookList);
        }

        public ActionResult Filter()
        {
            var Books = db.Books;
            return View(Books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Include(x => x.Files).SingleOrDefault(x => x.BooksID == id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }
        [Authorize(Roles = "canEdit")]
        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BooksID,Title,ISBN,Author,Publisher,Number,Available,ClassRoom")] Books books, HttpPostedFileBase upload)
        {
            // function to add photo to book id
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        var cover = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Photo,
                            ContentType = upload.ContentType
                        };

                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            cover.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        books.Files = new List<File> { cover };
                    }

                    db.Books.Add(books);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Unable to save changes. try again.");
            }

            return View(books);
        }
        [Authorize(Roles = "canEdit")]
        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Include(x => x.Files).SingleOrDefault(x => x.BooksID == id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind(Include = "BooksID,Title,ISBN,Author,Publisher,Number,Available,ClassRoom")] Books books, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Very long function to detect if a photo exists on this book id. Delete it then replace it will the supplied photo.
            var updateBook = db.Books.Find(books.BooksID);

            if (TryUpdateModel(updateBook, "",
        new string[] { "BooksID", "Title", "ISBN", "Author", "Publisher", "Number", "Available", "ClassRoom" }))
            {

            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (updateBook.Files.Any(x => x.FileType == FileType.Photo))
                        {
                            db.Files.Remove(updateBook.Files.First(x => x.FileType == FileType.Photo));

                        }

                        var photo = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Photo,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            photo.Content = reader.ReadBytes(upload.ContentLength);
                        }

                        updateBook.Files = new List<File> { photo };


                        db.Entry(updateBook).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to add a profile image.");
                }

            }
            db.Entry(updateBook).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "canEdit")]
        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Books books = db.Books.Find(id);
            if (books == null)
            {
                return HttpNotFound();
            }
            return View(books);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Books books = db.Books.Find(id);
            db.Books.Remove(books);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JCold_UVU_MVC_Inventory/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCold_UVU_MVC_Inventory.Models;

namespace JCold_UVU_MVC_Inventory.Controllers
{
    [Authorize(Roles = "canEdit")]
    public class StudentsController : Controller
    {
        private JCold_UVU_MVC_InventoryDb db = new JCold_UVU_MVC_InventoryDb();
        // GET: Students
        public ActionResult Index(int? id)
        {

            Students students = db.Students.Find(id);
            //TODO Figure out if counting the amount of checkedout books by StudentID is possible. 

            // Queries to check if Students have checkedout books and to switch a bool if true or false
            var UpdateQueryBooks =
               from chks in db.CheckOutBooks
               join st in db.Students
               on chks.StudentsID equals st.StudentsID
               where chks.StudentsID == st.StudentsID && chks.ReturnedBook == false
               select st;
            foreach (Students chks in UpdateQueryBooks)
            {
                chks.HasCheckedOutBooks = true;
            }

            var ResetUpdateQueryBooksOnReturn =
               from chks in db.CheckOutBooks
               join st in db.Students
               on chks.StudentsID equals st.StudentsID
               where chks.ReturnedBook == true
               select st;
            foreach (Students chkb in ResetUpdateQueryBooksOnReturn)
            {
                chkb.HasCheckedOutBooks = false;
            }

            var ResetUpdateQueryBooksOnDelete =
                from st in db.Students
                where !(from ch in db.CheckOutBooks select ch.StudentsID).Contains(st.StudentsID)
                select st;
            foreach (Students chkb in ResetUpdateQueryBooksOnDelete)
            {
                chkb.HasCheckedOutBooks = false;
            }


            // Queries to check if Students have checkedout supplies and to switch a bool if true or false
            var ResetUpdateQuerySuppliesOnReturn =
               from chks in db.CheckOutSupplies
               join st in db.Students
               on chks.StudentsID equals st.StudentsID
               where chks.ReturnedSupply == true
               select st;
            foreach (Students chkb in ResetUpdateQuerySuppliesOnReturn)
            {
                chkb.HasCheckedOutSupplies = false;
            }

            var ResetUpdateQuerySuppliesOnDelete =
                from st in db.Students
                where !(from ch in db.CheckOutSupplies select ch.StudentsID).Contains(st.StudentsID)
                select st;
            foreach (Students chkb in ResetUpdateQuerySuppliesOnDelete)
            {
                chkb.HasCheckedOutSupplies = false;
            }

            var UpdateQuerySupplies =
               from chks in db.CheckOutSupplies
               join st in db.Students
               on chks.StudentsID equals st.StudentsID
               where chks.StudentsID == st.StudentsID && chks.ReturnedSupply == false
               select st;
            foreach (Students chks in UpdateQuerySupplies)
            {
                chks.HasCheckedOutSupplies = true;
            }

            // Save each change to database
            db.SaveChanges();
            return View(db.Students.ToList());
        }

        [Authorize(Roles = "canEdit")]
        public ActionResult Search(string studentName)
        {
            List<Students> studentList = db.Students.Where(x => x.StudentName.Contains(studentName) | x.UVUID.Contains(studentName)).ToList();
            return View(studentList);
        }

        [Authorize(Roles = "canEdit")]
        public ActionResult Filter()
        {
            var Students = db.Students;
            return View(Students.ToList());
        }

        [Authorize(Roles = "canEdit")]
        // GET: Students/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }

            var CheckedBooksSelectQuery =
                from chks in db.CheckOutBooks
                 join st in db.Students
                 on chks.StudentsID equals st.StudentsID join bk in db.Books
                 on chks.BooksID equals bk.BooksID
                 where chks.StudentsID == id && chks.ReturnedBook == false
                 select new { bk.Title,bk.ISBN, bk.Number, bk.ClassRoom, chks.Department.DepName, chks.CheckedOutDate, chks.DueDate};


            var CheckedSuppliesSelectQuery =
                from chks in db.CheckOutSupplies
                 join st in db.Students
                 on chks.StudentsID equals st.StudentsID join bk in db.Supplies
                 on chks.SuppliesID equals bk.SuppliesID
                 where chks.StudentsID == id && chks.ReturnedSupply == false
                 select new { bk.Name,bk.Number, bk.Value, bk.ClassRoom, chks.Department.DepName, chks.CheckedOutDate, chks.DueDate};

            ViewBag.CheckSuppliesQuery = CheckedSuppliesSelectQuery;
            ViewBag.CheckBookQuery = CheckedBooksSelectQuery;

            return View(students);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Students/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentsID,UVUID,StudentName,StudentEmail,StudentPhone,HasCheckedOutBooks,HasCheckedOutSupplies")] Students students)
        {
            if (ModelState.IsValid)
            {
                db.Students.Add(students);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(students);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Students/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentsID,UVUID,StudentName,StudentEmail,StudentPhone,HasCheckedOutBooks,HasCheckedOutSupplies")] Students students)
        {
            if (ModelState.IsValid)
            {
                db.Entry(students).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(students);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Students/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Students students = db.Students.Find(id);
            if (students == null)
            {
                return HttpNotFound();
            }
            return View(students);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Students students = db.Students.Find(id);
            db.Students.Remove(students);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JCold_UVU_MVC_Inventory/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table grid-table table-responsive-xl">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

JCold_UVU_MVC_Inventory/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

JCold_UVU_MVC_Inventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - UISB</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/Gridmvc.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />


    <link href="~/Content/datepicker.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script src="~/Scripts/gridmvc.js"></script>




</head>
<body>


    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container">
            
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Home")" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item ">
                        <a href="@Url.Action("Index", "Books")" class="nav-link">Books</a>
                    </li>
                    <li class="nav-item ">
                        <a href="@Url.Action("Index", "Supplies")" class="nav-link">Supplies</a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Departments")" class="nav-link">Departments</a>
                    </li>
                    @if (User.IsInRole("canEdit"))
    {
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Students")" class="nav-link">Students</a>
                </li>
}

                    @if (User.IsInRole("canEdit"))
    {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Check out
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="@Url.Action("Index", "CheckOutBooks")">Books</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "CheckOutSupplies")">Supplies</a>
                    </div>
                </li>
}
                </ul>
                    <br />
                    @Html.Partial("_LoginPartial")
                    <br />
                </div>
            </div>
        </nav>




        <br />
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Team UISB</p>
            </footer>
        </div>

        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @Scripts.Render("~/bundles/jqueryui")
        @RenderSection("scripts", required: false)

    </body>
</html>