JCold_UVU_MVC_Inventory/Controllers/SuppliesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCold_UVU_MVC_Inventory.Models;

namespace JCold_UVU_MVC_Inventory.Controllers
{
    public class SuppliesController : Controller
    {
        private JCold_UVU_MVC_InventoryDb db = new JCold_UVU_MVC_InventoryDb();

        // GET: Supplies
        public ActionResult Index()
        {
            var SetAvailableSuppliesTrue =
            from chkb in db.CheckOutSupplies
            join bk in db.Supplies
            on chkb.SuppliesID equals bk.SuppliesID
            where chkb.SuppliesID == bk.SuppliesID && chkb.ReturnedSupply == true
            select bk;
            foreach (Supplies chkb in SetAvailableSuppliesTrue)
            {
                chkb.Available = true;
            }

            var SetAvailableSuppliesFalse =
            from chkb in db.CheckOutSupplies
            join bk in db.Supplies
            on chkb.SuppliesID equals bk.SuppliesID
            where chkb.SuppliesID == bk.SuppliesID && chkb.ReturnedSupply == false
            select bk;
            foreach (Supplies chkb in SetAvailableSuppliesFalse)
            {
                chkb.Available = false;
            }

            var ResetUpdateQuerySuppliesOnDelete =
            from st in db.Supplies
            where !(from ch in db.CheckOutSupplies select ch.SuppliesID).Contains(st.SuppliesID)
            select st;
            foreach (Supplies chkb in ResetUpdateQuerySuppliesOnDelete)
            {
                chkb.Available = true;
            }
            db.SaveChanges();
            return View(db.Supplies.ToList());
        }

        public ActionResult Search(string supplyName)
        {
            List<Supplies> supplyList = db.Supplies.Where(x => x.Name.Contains(supplyName) | x.ClassRoom.Contains(supplyName)).ToList();
            return View(supplyList);
        }
        public ActionResult Filter()
        {
            var Supplies = db.Supplies;
            return View(Supplies.ToList());
        }

        // GET: Supplies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplies supplies = db.Supplies.Find(id);
            if (supplies == null)
            {
                return HttpNotFound();
            }
            return View(supplies);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Supplies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Supplies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SuppliesID,Name,Value,Number,Available,ClassRoom")] Supplies supplies, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        var cover = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Photo,
                            ContentType = upload.ContentType
                        };

                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            cover.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        supplies.Files = new List<File> { cover };
                    }

                    db.Supplies.Add(supplies);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (RetryLimitExceededException)
            {
                ModelState.AddModelError("", "Unable to save changes. try again.");
            }

            return View(supplies);
        }

        [Authorize(Roles = "canEdit")]
        // GET: Supplies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplies supplies = db.Supplies.Find(id);
            if (supplies == null)
            {
                return HttpNotFound();
            }
            return View(supplies);
        }

        // POST: Supplies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, [Bind(Include = "SuppliesID,Name,Value,Number,Available,ClassRoom")] Supplies supplies, HttpPostedFileBase upload)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // Very long function to detect if a photo exists on this supply id. Delete it then replace it will the supplied photo.
            var updateSupply = db.Supplies.Find(supplies.SuppliesID);

            if (TryUpdateModel(updateSupply, "",
        new string[] { "SuppliesID","Name","Value","Number","Available","ClassRoom" }))
            {

            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        if (updateSupply.Files.Any(x => x.FileType == FileType.Photo))
                        {
                            db.Files.Remove(updateSupply.Files.First(x => x.FileType == FileType.Photo));

                        }

                        var photo = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Photo,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            photo.Content = reader.ReadBytes(upload.ContentLength);
                        }

                        updateSupply.Files = new List<File> { photo };


                        db.Entry(updateSupply).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (RetryLimitExceededException)
                {
                    ModelState.AddModelError("", "Unable to add a profile image.");
                }

            }
            db.Entry(updateSupply).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "canEdit")]
        // GET: Supplies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Supplies supplies = db.Supplies.Find(id);
            if (supplies == null)
            {
                return HttpNotFound();
            }
            return View(supplies);
        }

        // POST: Supplies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplies supplies = db.Supplies.Find(id);
            db.Supplies.Remove(supplies);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JCold_UVU_MVC_Inventory/Views/Supplies/Create.cshtml
@model JCold_UVU_MVC_Inventory.Models.Supplies

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Supplies", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Supplies</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Wooden Catapult" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control", @placeholder = "100.00" } })
            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control", @placeholder = "0" } })
            @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClassRoom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassRoom, new { htmlAttributes = new { @class = "form-control", @placeholder = "INFO-9999" } })
            @Html.ValidationMessageFor(model => model.ClassRoom, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Supply Photo", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="SupplyPhoto" name="upload" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary btn-block" />
            <br />
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCold_UVU_MVC_Inventory/Views/Supplies/Delete.cshtml
@model JCold_UVU_MVC_Inventory.Models.Supplies

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplies</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.ClassRoom)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()



        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Delete
        </button>
        <br />
        <br />
        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Are you sure?</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="alert alert-danger" role="alert">
                            This will delete all records that contain this supply entry on the check out supplies page.
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="modal-body">
                            <div class="form-actions no-color">
                                <input type="submit" value="Yes" class="btn btn-danger" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

JCold_UVU_MVC_Inventory/Views/Supplies/Details.cshtml
@model JCold_UVU_MVC_Inventory.Models.Supplies

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Supplies</h4>
    <hr />
    <div class=" clearfix">
        @if (Model.Files.Any(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo))
        {
            <p>
                <img class="img-fluid" src="~/File?id=@Model.Files.First(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo).FileId" alt="Profile Image" width="250" />
            </p>
        }
    </div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Number)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Number)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassRoom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassRoom)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("canEdit"))
    {
    <a href="@Url.Action("Edit", "Supplies", new { id = Model.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
    }
    <a href="@Url.Action("Index", "Supplies", new { id = Model.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Back To List</a>
</p>

JCold_UVU_MVC_Inventory/Views/Supplies/Edit.cshtml
@model JCold_UVU_MVC_Inventory.Models.Supplies

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Supplies", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Supplies</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.SuppliesID)

    <div class=" clearfix">
        @if (Model.Files.Any(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo))
        {
            <p>
                <img class="img-fluid" src="~/File?id=@Model.Files.First(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo).FileId" alt="Profile Image" width="250" />
            </p>
        }
    </div>
    <div class="form-group">
        @Html.Label("Picture", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Cover" name="upload" />
        </div>
    </div>

    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ClassRoom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ClassRoom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ClassRoom, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-info" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCold_UVU_MVC_Inventory/Views/Supplies/Filter.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.Supplies>

@{
    ViewBag.Title = "Filter";
}

@using GridMvc.Html

<h2><i class="fa fa-lg fa-search "></i>Filter</h2>
<br />
<br />
@if (User.IsInRole("canEdit"))
{
    <a href="@Url.Action("Create", "Supplies")" style="color: white" class="btn btn-primary">Create Supply</a>
}
    <a href="@Url.Action("Index", "Supplies")" style="color: white" class="btn btn-secondary">Back</a>
    <br />
    <p></p>

    @Html.Grid(Model).Columns(c =>
    {
        c.Add(d => d.Name).Titled("Name");
        c.Add(d => d.Value).Titled("Value");
        c.Add(d => d.Number).Titled("#");
        c.Add(d => d.Available).Titled("Available");
        c.Add(d => d.ClassRoom).Titled("Class Room");
        c.Add().Encoded(false).Sanitized(false).RenderValueAs(o => (
    @<b>
        @if (User.IsInRole("canEdit"))
                        {
            <a href="@Url.Action("Edit", "Supplies", new { id = o.SuppliesID })"><i class="fa  fa-lg fa-pencil-square" title="Edit"></i></a>
                        }
        
        <a href="@Url.Action("Details", "Supplies", new {id = o.SuppliesID })"><i class="fa fa-lg fa-info-circle" title="Details"></i></a>
        @if (User.IsInRole("canEdit"))
                        {
            <a href="@Url.Action("Delete", "Supplies", new { id = o.SuppliesID })"><i class="fa fa-lg fa-times-circle" title="Delete"></i></a>
                        }
        
    </b>));
                }).Sortable(true).Filterable(true).WithPaging(10).WithMultipleFilters()

JCold_UVU_MVC_Inventory/Views/Supplies/Index.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.Supplies>

@{
    ViewBag.Title = "Supplies";
}

<h2><i class="fa fa-lg fa-pencil"></i> Supplies</h2>

@using (Html.BeginForm("Search", "Supplies", FormMethod.Get, new { @class = "form-inline" }))
{
    <input type="text" class="form-control" size="30" name="supplyName" placeholder="Search Name, Class Room" />
    <input type="submit" class="btn btn-default" value="Search" />
}
<br />
<br />
<p>
    @if (User.IsInRole("canEdit"))
    {
        <a href="@Url.Action("Create", "Supplies")" style="color: white" class="btn btn-primary">Create Supply</a>
    }
    <a href="@Url.Action("Filter", "Supplies")" style="color: white" class="btn btn-primary">Filter</a>
</p>
<table class="table">
    <tr>
        @*<th>
                Picture
            </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassRoom)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            @*<td>
                    <div class=" clearfix">
                        @if (item.Files.Any(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo))
                        {
                            <p>
                                <img class="img-fluid" src="~/File?id=@item.Files.First(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo).FileId" alt="Profile Image" width="60" />
                            </p>
                        }
                    </div>
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>

            <td>
                @if (@item.Available)
                {
                    <i class="fa fa-lg fa-check-circle" style="color: forestgreen"></i>
                }
                else
                {
                    <i class="fa fa-lg fa-times-circle" style="color: darkred"></i>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassRoom)
            </td>
            <td>
                @if (User.IsInRole("canEdit"))
                {
                    <a href="@Url.Action("Edit", "Supplies", new { id = item.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
                }
                <a href="@Url.Action("Details", "Supplies", new { id = item.SuppliesID})" style="color: black" class="btn btn-sm btn-light">Details</a>
                @if (User.IsInRole("canEdit"))
                {
                    <a href="@Url.Action("Delete", "Supplies", new { id = item.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Delete</a>
                }
                @if (item.Files.Any(x => x.FileType == JCold_UVU_MVC_Inventory.Models.FileType.Photo))
                {
                    <a href="@Url.Action("Details", "Supplies", new { id = item.SuppliesID})" class="fa fa-camera" style="color:black"></a>
                }
            </td>
        </tr>
    }

</table>

JCold_UVU_MVC_Inventory/Views/Supplies/Search.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.Supplies>

@{
    ViewBag.Title = "Search";
}

<h2><i class="fa fa-lg fa-search"></i> Search Supplies </h2>

@using (Html.BeginForm("Search", "Supplies", FormMethod.Get, new { @class = "form-inline" }))
{
    <input type="text" class="form-control" size="30" name="supplyName" placeholder="Search Name, Class Room" />
    <input type="submit" class="btn btn-default" value="Search" />
}
<br />
<br />
<p>
    @if (User.IsInRole("canEdit"))
    {
        <a href="@Url.Action("Create", "Supplies")" style="color: white" class="btn btn-primary">Create Supply</a>
    }
</p>
<br />
<h3>Search Results:</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Available)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassRoom)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Value)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Number)
            </td>
            <td>
                @if (@item.Available)
                {
                    <i class="fa fa-lg fa-check-circle" style="color: forestgreen"></i>
                }
                else
                {
                    <i class="fa fa-lg fa-times-circle" style="color: darkred"></i>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ClassRoom)
            </td>
            <td>
                @if (User.IsInRole("canEdit"))
                {
                <a href="@Url.Action("Edit", "Supplies", new { id = item.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
                }
                <a href="@Url.Action("Details", "Supplies", new { id = item.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Details</a>
                @if (User.IsInRole("canEdit"))
                {
                <a href="@Url.Action("Delete", "Supplies", new { id = item.SuppliesID })" style="color: black" class="btn btn-sm btn-light">Delete</a>
                }
            </td>
        </tr>
    }

</table>