JCold_UVU_MVC_Inventory/Models/CheckOutBook.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace JCold_UVU_MVC_Inventory.Models
{
    public class CheckOutBook
    {
        public int CheckOutBookID { get; set; }
        public int StudentsID { get; set; }
        [Required(ErrorMessage ="A book is required")]
        public int BooksID { get; set; }
        public int DepartmentID { get; set; }
        [Column(TypeName ="datetime2")]
        public DateTime DueDate { get; set; }
        [Display(Name = "Returned")]
        public bool ReturnedBook { get; set; }
        [Column(TypeName = "datetime2")]
        [Display(Name ="Returned Date")]
        public DateTime? ReturnedDate { get; set; }
        [Column(TypeName = "datetime2")]
        [Display(Name ="Checked out Date")]
        public DateTime CheckedOutDate { get; set; }
        public virtual Students Students { get; set; }
        public virtual Books Books { get; set; }
        public virtual Department Department { get; set; }
    }
}

JCold_UVU_MVC_Inventory/Controllers/CheckOutBooksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JCold_UVU_MVC_Inventory.Models;

namespace JCold_UVU_MVC_Inventory.Controllers
{
    [Authorize(Roles = "canEdit")]
    public class CheckOutBooksController : Controller
    {
        private JCold_UVU_MVC_InventoryDb db = new JCold_UVU_MVC_InventoryDb();
        


        // GET: CheckOutBooks
        public ActionResult Index()
        {
            

            var checkOutBooks = db.CheckOutBooks.Include(c => c.Books).Include(c => c.Department).Include(c => c.Students);
            return View(checkOutBooks.ToList().OrderByDescending(p => p.CheckedOutDate));
        }

        public ActionResult Search(string checkoutbookstring, bool checkBookResp = true)
        {
                List<CheckOutBook> checkedoutbooklist = db.CheckOutBooks.Where(x => x.ReturnedBook.Equals(checkBookResp)).ToList();
                return View(checkedoutbooklist);
        }

        public ActionResult Filter()
        {
            var checkOutBooks = db.CheckOutBooks.Include(c => c.Books).Include(c => c.Department).Include(c => c.Students);
            return View(checkOutBooks.ToList());
        }


        
        [HttpPost]
        public JsonResult AutoCompleteBooks(string Prefix)
        {
            var Books = (from c in db.Books
                         where c.Title.ToLower().Contains(Prefix.ToLower()) | c.ClassRoom.ToLower().Contains(Prefix.ToLower())
                         select new {c.BooksID, c.Title, c.ISBN, c.Number, c.ClassRoom });

            return Json(Books, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult AutoCompleteStudents(string Prefix)
        {
            var Students = (from c in db.Students
                         where c.StudentName.ToLower().Contains(Prefix.ToLower()) | c.UVUID.ToLower().Contains(Prefix.ToLower())
                            select new { c.StudentsID, c.StudentName, c.UVUID});

            return Json(Students, JsonRequestBehavior.AllowGet);
        }

        // GET: CheckOutBooks/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOutBook checkOutBook = db.CheckOutBooks.Find(id);
            if (checkOutBook == null)
            {
                return HttpNotFound();
            }
            return View(checkOutBook);
        }

        // GET: CheckOutBooks/Create
        public ActionResult Create()
        {
            // Defining Values to pass into ViewBag below selectListStudents and Books
            var students = db.Students.Where(s => s.StudentsID == s.StudentsID).ToList();
            IEnumerable<SelectListItem>
                selectListStudents = from s in students
                                     select new SelectListItem
                                     {
                                         Value = s.StudentsID.ToString(),
                                         Text = s.StudentName + ", UVUID: " + s.UVUID + "  "
                                     };

            var books = db.Books.Where(s => s.BooksID == s.BooksID).ToList();
            IEnumerable<SelectListItem>
                selectListBooks = from s in books
                                     select new SelectListItem
                                     {
                                         Value = s.BooksID.ToString(),
                                         Text = s.Title + ", ISBN: " + s.ISBN + ", Number: " + s.Number + ", Class Room: " + s.ClassRoom + " "
                                     };

            ViewBag.BooksID = new SelectList(selectListBooks, "Value", "Text");
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepName");
            ViewBag.StudentsID = new SelectList(selectListStudents, "Value", "Text");

            CheckOutBook model = new CheckOutBook();
            model.CheckedOutDate = DateTime.Now;
            model.DueDate = DateTime.Now.AddDays(7);
            return View(model);
        }

        // POST: CheckOutBooks/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CheckOutBookID,StudentsID,BooksID,DepartmentID,DueDate,ReturnedBook,ReturnedDate,CheckedOutDate")] CheckOutBook checkOutBook)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    db.CheckOutBooks.Add(checkOutBook);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch
                {
                    return Content("check out request was invalid go back and try again");
                }
                
            }

            ViewBag.BooksID = new SelectList(db.Books, "BooksID", "Title", checkOutBook.BooksID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepName", checkOutBook.DepartmentID);
            ViewBag.StudentsID = new SelectList(db.Students, "StudentsID", "StudentName", checkOutBook.StudentsID);
            return View(checkOutBook);

        }

        // GET: CheckOutBooks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOutBook checkOutBook = db.CheckOutBooks.Find(id);
            if (checkOutBook == null)
            {
                return HttpNotFound();
            }
            // Defining Values to pass into ViewBag below selectListStudents and Books
            var students = db.Students.Where(s => s.StudentsID == s.StudentsID).ToList();
            IEnumerable<SelectListItem>
                selectListStudents = from s in students
                                     select new SelectListItem
                                     {
                                         Value = s.StudentsID.ToString(),
                                         Text = s.StudentName + ", UVUID: " + s.UVUID + "  "
                                     };

            var books = db.Books.Where(s => s.BooksID == s.BooksID).ToList();
            IEnumerable<SelectListItem>
                selectListBooks = from s in books
                                  select new SelectListItem
                                  {
                                      Value = s.BooksID.ToString(),
                                      Text = s.Title + ", ISBN: " + s.ISBN + ", Number: " + s.Number + ", Class Room: " + s.ClassRoom + " "
                                  };
            ViewBag.BooksID = new SelectList(selectListBooks, "Value", "Text", checkOutBook.BooksID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepName", checkOutBook.DepartmentID);
            ViewBag.StudentsID = new SelectList(selectListStudents, "Value", "Text", checkOutBook.StudentsID);
            return View(checkOutBook);
        }

        // POST: CheckOutBooks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CheckOutBookID,StudentsID,BooksID,DepartmentID,DueDate,ReturnedBook,ReturnedDate,CheckedOutDate")] CheckOutBook checkOutBook)
        {
            if (checkOutBook.ReturnedBook)
            {
                DateTime CurrentDate = DateTime.Now;
                checkOutBook.ReturnedDate = CurrentDate;
                db.Entry(checkOutBook).State = EntityState.Modified;
            }
            if (ModelState.IsValid)
            {
                db.Entry(checkOutBook).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BooksID = new SelectList(db.Books, "BooksID", "Title", checkOutBook.BooksID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "DepartmentID", "DepName", checkOutBook.DepartmentID);
            ViewBag.StudentsID = new SelectList(db.Students, "StudentsID", "StudentName", checkOutBook.StudentsID);
            return View(checkOutBook);
        }

        // GET: CheckOutBooks/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckOutBook checkOutBook = db.CheckOutBooks.Find(id);
            if (checkOutBook == null)
            {
                return HttpNotFound();
            }
            return View(checkOutBook);
        }

        // POST: CheckOutBooks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CheckOutBook checkOutBook = db.CheckOutBooks.Find(id);
            db.CheckOutBooks.Remove(checkOutBook);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Create.cshtml
@model JCold_UVU_MVC_Inventory.Models.CheckOutBook

@{
    ViewBag.Title = "Check out books";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Check out a Book</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <!-- Begin Jquery ui books autocomplete-->
    <div class="form-group">
        @Html.LabelFor(model => model.BooksID, "Book", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" id="BooksID" placeholder="Search Book Titles/Class Room" />
            @Html.HiddenFor(model => model.BooksID, new { @id = "hidden_bookid" })
            @Html.ValidationMessageFor(model => model.BooksID, "", new { @class = "text-danger" })

            <script type="text/javascript">
                $(document).ready(function () {
                    $("#BooksID").autocomplete({
                        source: function (request, response) {
                            $.ajax({
                                url: "AutoCompleteBooks",
                                type: "POST",
                                dataType: "json",
                                data: { Prefix: request.term },
                                success: function (data) {
                                    response($.map(data, function (item) {
                                        return {
                                            label: item.Title + ', ISBN: ' + item.ISBN + ', Number: #' + item.Number + ', Class Room: ' + item.ClassRoom,
                                            value: item.Title + ', ISBN: ' + item.ISBN + ', Number: #' + item.Number + ', Class Room: ' + item.ClassRoom,
                                            id: item.BooksID
                                        };
                                    }))

                                }
                            })
                        },
                        messages: {
                            noResults: "",
                            results: function (count) {
                                return count + (count > 1 ? ' results' : ' result ') + ' found';
                            }
                        },
                        select: function (event, ui) {
                            $('#hidden_bookid').val(ui.item.id)
                        }
                    });
                })
            </script>
        </div>
    </div>
    <!-- End Jquery ui books autocomplete-->
    <!-- Begin Jquery ui students autocomplete-->
    <div class="form-group">
        @Html.LabelFor(model => model.StudentsID, "Student", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input class="form-control" id="StudentsID" placeholder="Search Student Name/UVUID" />
            @Html.HiddenFor(model => model.StudentsID, new { @id = "hidden_studentid" })
            @Html.ValidationMessageFor(model => model.StudentsID, "", new { @class = "text-danger" })

            <script type="text/javascript">
                $(document).ready(function () {
                    $("#StudentsID").autocomplete({
                        source: function (request, response) {
                            $.ajax({
                                url: "AutoCompleteStudents",
                                type: "POST",
                                dataType: "json",
                                data: { Prefix: request.term },
                                success: function (data) {
                                    response($.map(data, function (item) {
                                        return {
                                            label: item.StudentName + ', UVUID: ' + item.UVUID,
                                            value: item.StudentName + ', UVUID: ' + item.UVUID,
                                            id: item.StudentsID
                                        };
                                    }))

                                }
                            })
                        },
                        messages: {
                            noResults: "",
                            results: function (count) {
                                return count + (count > 1 ? ' results' : ' result ') + ' found';
                            }
                        },
                        select: function (event, ui) {
                            $('#hidden_studentid').val(ui.item.id)
                        }
                    });
                })
            </script>
        </div>
    </div>
    <!-- End Jquery ui students autocomplete-->

    <div class="form-group">
        @Html.LabelFor(model => model.DepartmentID, "Department", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("DepartmentID", null, "Select a Department", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.DepartmentID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CheckedOutDate, "Check out Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CheckedOutDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CheckedOutDate, "", new { @class = "text-danger" })
            <script>
                $(function () {
                    $("#CheckedOutDate").datepicker();
                });
            </script>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DueDate, "Due Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DueDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CheckedOutDate, "", new { @class = "text-danger" })
            <script>
                $(function () {
                    $("#DueDate").datepicker();
                });
            </script>
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Check out" class="btn btn-primary btn-block" />
            <br />
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Delete.cshtml
@model JCold_UVU_MVC_Inventory.Models.CheckOutBook

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CheckOutBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Books.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Books.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Students.StudentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Students.StudentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnedBook)
        </dt>

        <dd>
            @if(Model.ReturnedBook) {
                <i class="fa fa-lg fa-check-circle" style="color: forestgreen"></i>
                }
                else {
                <i class="fa fa-lg fa-times-circle" style="color: darkgoldenrod"></i>
                }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckedOutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckedOutDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Details.cshtml
@model JCold_UVU_MVC_Inventory.Models.CheckOutBook

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CheckOutBook</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Books.Title), ISBN, Number
        </dt>

        <dd>
            Title:
            @Html.DisplayFor(model => model.Books.Title),
            ISBN:
            @Html.DisplayFor(model => model.Books.ISBN),
            #@Html.DisplayFor(Model => Model.Books.Number),
            Class Room:
            @Html.DisplayFor(Model => Model.Books.ClassRoom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Department.DepName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Department.DepName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Students.StudentName), UVU ID, Email
        </dt>

        <dd>
            Name:
            @Html.DisplayFor(model => model.Students.StudentName),
            UVUID:
            @Html.DisplayFor(model => model.Students.UVUID),
            Email:
            @Html.DisplayFor(model => model.Students.StudentEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnedBook)
        </dt>

        <dd>
            @if (Model.ReturnedBook)
            {
                <p>Yes</p>
            }
            else
            {
                <p>No</p>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DueDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DueDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReturnedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReturnedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckedOutDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckedOutDate)
        </dd>

    </dl>
</div>
<p>
    <a href="@Url.Action("Edit", "CheckOutBooks", new { id = Model.CheckOutBookID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
    <a href="@Url.Action("Index", "CheckOutBooks", new { id = Model.CheckOutBookID })" style="color: black" class="btn btn-sm btn-light">Back To List</a>
</p>

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Filter.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.CheckOutBook>

@{
    ViewBag.Title = "Filter";
}

@using GridMvc.Html

<h2><i class="fa fa-lg fa-search "></i>Filter</h2>
<br />
<br />
<a href="@Url.Action("Create", "CheckOutBooks")" style="color: white" class="btn btn-primary">Check out</a>
<a href="@Url.Action("Index", "CheckOutBooks")" style="color: white" class="btn btn-secondary">Back</a>
<br />
<p></p>

@Html.Grid(Model).Columns(c =>
{
    c.Add(d => d.Books.Title).Titled("Book");
    c.Add(d => d.Books.ClassRoom).Titled("Class Room");
    c.Add(d => d.Books.Number).Titled("#");
    c.Add(d => d.Department.DepName).Titled("Department");
    c.Add(d => d.Students.StudentName).Titled("Student");
    c.Add(d => d.ReturnedBook).Titled("Returned");
    c.Add(d => d.DueDate).Titled("Due Date");
    c.Add(d => d.ReturnedDate).Titled("Returned Date");
    c.Add(d => d.CheckedOutDate).Titled("Checked out Date");
    c.Add().Encoded(false).Sanitized(false).RenderValueAs(o => (
@<b>
    <a href="@Url.Action("Edit", "CheckOutBooks", new {id = o.CheckOutBookID })"><i class="fa  fa-lg fa-pencil-square" title="Edit"></i></a>
    <a href="@Url.Action("Details", "CheckOutBooks", new {id = o.CheckOutBookID })"><i class="fa fa-lg fa-info-circle" title="Details"></i></a>
    <a href="@Url.Action("Delete", "CheckOutBooks", new {id = o.CheckOutBookID })"><i class="fa fa-lg fa-times-circle" title="Delete"></i></a>
</b>));
        }).Sortable(true).Filterable(true).WithPaging(10).WithMultipleFilters()

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Index.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.CheckOutBook>

@{
    ViewBag.Title = "Check out Books";
}


<h2><i class="fa fa-lg fa-calendar-check-o "></i> Check out Books</h2>

<br />
<br />
<p>
    <a href="@Url.Action("Create", "CheckOutBooks")" style="color: white" class="btn btn-primary">Check out</a>
    <a href="@Url.Action("Filter", "CheckOutBooks")" style="color: white" class="btn btn-primary">Filter</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Books.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Students.StudentName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnedBook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckedOutDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Books.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Department.DepName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Students.StudentName)
            </td>

            <td>
                @if (@item.ReturnedBook)
                {
                    <i class="fa fa-lg fa-check-circle" style="color: forestgreen"></i>
                }
                else
                {
                    <i class="fa fa-lg fa-times-circle" style="color: darkgoldenrod"></i>
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DueDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReturnedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckedOutDate)
            </td>
            <td>
                <a href="@Url.Action("Edit", "CheckOutBooks", new { id = item.CheckOutBookID })" style="color: black" class="btn btn-sm btn-light">Edit</a>
                <a href="@Url.Action("Details", "CheckOutBooks", new { id = item.CheckOutBookID })" style="color: black" class="btn btn-sm btn-light">Details</a>
                <a href="@Url.Action("Delete", "CheckOutBooks", new { id = item.CheckOutBookID })" style="color: black" class="btn btn-sm btn-light">Delete</a>
            </td>
        </tr>
    }

</table>

JCold_UVU_MVC_Inventory/Views/CheckOutBooks/Search.cshtml
@model IEnumerable<JCold_UVU_MVC_Inventory.Models.CheckOutBook>

@{
    ViewBag.Title = "Search";
}
<!--TODO Stylize buttons and Search Page-->
<h2>Search</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Books.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Department.DepName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Students.UVUID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnedBook)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReturnedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckedOutDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Books.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department.DepName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Students.UVUID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnedBook)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReturnedDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckedOutDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CheckOutBookID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CheckOutBookID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CheckOutBookID })
        </td>
    </tr>
}

</table>